In [6]:
# ライブラリの読み込み
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

from scipy import stats
from scipy.stats import norm, skew #for some statistics

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

%matplotlib inline

### データの読み込み

In [7]:
train_df = pd.read_csv(r'../data/train.csv',)
test_df = pd.read_csv(r'../data/test.csv')

In [8]:
train_df.reset_index(drop=True, inplace=True)
train_df.head()

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,Male,24.443011,1.699998,81.669950,yes,yes,2.000000,2.983297,Sometimes,no,2.763573,no,0.000000,0.976473,Sometimes,Public_Transportation,Overweight_Level_II
1,1,Female,18.000000,1.560000,57.000000,yes,yes,2.000000,3.000000,Frequently,no,2.000000,no,1.000000,1.000000,no,Automobile,Normal_Weight
2,2,Female,18.000000,1.711460,50.165754,yes,yes,1.880534,1.411685,Sometimes,no,1.910378,no,0.866045,1.673584,no,Public_Transportation,Insufficient_Weight
3,3,Female,20.952737,1.710730,131.274851,yes,yes,3.000000,3.000000,Sometimes,no,1.674061,no,1.467863,0.780199,Sometimes,Public_Transportation,Obesity_Type_III
4,4,Male,31.641081,1.914186,93.798055,yes,yes,2.679664,1.971472,Sometimes,no,1.979848,no,1.967973,0.931721,Sometimes,Public_Transportation,Overweight_Level_II

In [9]:
# Id列削除前の型を確認
print("The train_df data size before dropping Id feature is : {} ".format(train_df.shape))
print("The test_df data size before dropping Id feature is : {} ".format(test_df.shape))

# Idだけ別に保持する
train_df_ID = train_df['id']
test_df_ID = test_df['id']

# 予測に不要なのでId列を削除する
train_df.drop("id", axis = 1, inplace = True)
test_df.drop("id", axis = 1, inplace = True)

# Id列削除後の型を確認
print("\nThe train_df data size after dropping Id feature is : {} ".format(train_df.shape)) 
print("The test_df data size after dropping Id feature is : {} ".format(test_df.shape))

The train_df data size before dropping Id feature is : (20758, 18)
The test_df data size before dropping Id feature is : (13840, 17)

The train_df data size after dropping Id feature is : (20758, 17)
The test_df data size after dropping Id feature is : (13840, 16)

### データの前処理